[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapings = ["openzeppelin-contracts/=lib/openzeppelin-contracts"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config